### ISSUE TITLE
Veva Signature

### ISSUE THREAD

**Issue by hayden-gp** [IncendiaryCode/veva#2]
@gpashis As soon as you get a second can you put together an email signature for me for veva.  It can be exactly the same as Sphere but with the Veva logo and color - 170,0,0.

Also, our address is now 

1314 NW Irving St #414
Portland, OR  97209

**Comment by hayden-gp** [comment]
Here is the Sphere one, and the Veva logo

![image](https://user-images.githubusercontent.com/6862162/89377886-8b1c6d80-d6a7-11ea-833d-63a17c62bc63.png)


![Veva Logo 5-15-20](https://user-images.githubusercontent.com/6862162/89377947-ab4c2c80-d6a7-11ea-8457-9d9593fa1704.png)

**Comment by gpashis** [comment]
@hayden-gp Please use the html for email signature. All the images uploaded to veva server for reference.

[email-signature.zip](https://github.com/IncendiaryCode/veva/files/5029737/email-signature.zip)

Let me know for any changes.

**Comment by hayden-gp** [comment]
@gpashis Thanks.  This is great.  I'll sort out the links, etc.
