### ISSUE TITLE
Should increase view cart click area which it is clickable only on number.

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/veva#3]
Click area of cart icon which is there at top right corner should be increased.

<img width="1268" alt="Screen Shot 2020-08-20 at 11 30 40 AM" src="https://user-images.githubusercontent.com/41627571/90722600-c2f6f800-e2d8-11ea-94eb-9cb4d1b6a83b.png">

**Comment by hayden-gp** [comment]
Thanks.
