### ISSUE TITLE
On click of pricing at the top, not stopping exactly at pricing and screen scrolls up.

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/veva#4]
**Steps to reproduce**

1. Go to veva website.
2. Click on pricing.

**Expectation**
Should scroll to pricing exactly.

**Observation**
It is not stopping exactly at pricing and screen scrolls up.

<img width="1212" alt="Screen Shot 2020-08-20 at 11 35 18 AM" src="https://user-images.githubusercontent.com/41627571/90722857-3e58a980-e2d9-11ea-911c-fde3ebb64114.png">

**Comment by hayden-gp** [comment]
Looks like this has been fixed.  Took me right to pricing.
