### ISSUE TITLE
Privacy policy heading is hiding at privacy policy page.

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/veva#5]
**Steps to reproduce**

1. Open veva website.
2. Go to end of page.
3. Click on privacy policy.

**Expectation**
Privacy policy page should open and title should be visible.

**Observation**
Privacy policy heading is hiding.

<img width="1212" alt="Screen Shot 2020-08-20 at 11 37 59 AM" src="https://user-images.githubusercontent.com/41627571/90723048-9f807d00-e2d9-11ea-9b16-220872c3e5aa.png">

**Comment by hayden-gp** [comment]
Thanks
