### ISSUE TITLE
On click of contact we are loading previous page which we opened before .

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/veva#6]
**Steps to reproduce**

1. Open veva website.
2. Go to end of page.
3. Click on contact.

**Expectation**
Should open contact page.

**Observation**
Opening terms page.

<img width="1212" alt="Screen Shot 2020-08-20 at 11 41 32 AM" src="https://user-images.githubusercontent.com/41627571/90723368-3b11ed80-e2da-11ea-8a7f-206e12b7ed69.png">

**Comment by hayden-gp** [comment]
Thanks!
