### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/veva#7]
**1.Html tags are displaying in the following links**

https://veva.co/feed/

https://veva.co/comments/feed/

![a43](https://user-images.githubusercontent.com/41984345/90722767-123d2880-e2d9-11ea-8234-6ad4cd994f14.png)

![a90](https://user-images.githubusercontent.com/41984345/90722756-0ea9a180-e2d9-11ea-961e-07bf2ad0edaa.png)

![a10](https://user-images.githubusercontent.com/41984345/90722763-10736500-e2d9-11ea-9139-03a445aa5046.png)
.

**2.UI are not properly displaying in following links**
https://veva.co/product/subscription/?attribute_weeks=4+Weeks.
https://veva.co/2020/02/
https://veva.co/category/uncategorized/
![at2](https://user-images.githubusercontent.com/41984345/90722974-7b24a080-e2d9-11ea-8bf6-39b818a4a904.png)
![at1](https://user-images.githubusercontent.com/41984345/90722977-7c55cd80-e2d9-11ea-8923-3a36ccd54de6.png)

![a5t6](https://user-images.githubusercontent.com/41984345/90722965-765fec80-e2d9-11ea-8b8c-e8a6daaf54b8.png)

**Comment by Sujatagp** [comment]
Also it is asking permission to open through app at safari and Firefox.

<img width="1264" alt="Screen Shot 2020-08-20 at 11 13 49 AM" src="https://user-images.githubusercontent.com/41627571/90724071-8b3d7f80-e2db-11ea-86ce-7af888047244.png">

**Comment by hayden-gp** [comment]
@gpakshith @Sujatagp @gpashis Thanks.  I'll pass these on to Slobodan.
