### ISSUE TITLE
Optional notes should be above place order buttonAt billing.

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/veva#8]
At billing, optional notes field should be above place order button.

<img width="1267" alt="Screen Shot 2020-08-20 at 1 40 17 PM" src="https://user-images.githubusercontent.com/41627571/90734786-f17dce80-e2ea-11ea-9006-1866a31c5a3c.png">

**Comment by hayden-gp** [comment]
Thanks for this.  Closing it out.
